name: tads_app
description: Transparent, Anonymous Donation System
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  google_fonts: ^3.0.1
  dio: ^4.0.6
  retrofit: ^3.3.1
#  chuck_interceptor: ^1.1.1
  get_it: ^7.2.0
  dio_retry_plus: ^1.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  keyboard_dismisser: ^3.0.0
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  json_serializable: ^6.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/png/
    - assets/images/