name: tads_app
description: Transparent, Anonymous Donation System
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  dio: ^5.1.1
  retrofit: ^4.0.1
  get_it: ^7.2.0
  dio_retry_plus: ^1.0.3
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  keyboard_dismisser: ^3.0.0
  intl: ^0.18.0
  flutter_svg: ^2.0.4
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  go_router: ^6.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  retrofit_generator: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/png/